const PRODUCT_INFO = {
  name: 'Edu Champ',
  description: 'Generated by create next app',
  logoWhite: '/logo-white.png',
  logoMobile: '/logo-mobile.png',
  logoAside: '/logo-aside.png',
  favicon: '/favicon.png',
  taskCard: '/task-card-image.jpg',
  hamkor1: '/hamkor1.png',
  hamkor2: '/hamkor2.jpg',
  hamkor3: '/hamkor3.svg',
  url: 'https://www.shadcnblocks.com',
  socials: {
    telegram: 'https://t.me/usmanov_dev',
    instagram: 'https://t.me/usmanov_dev',
    youtube: 'https://t.me/usmanov_dev',
    linkedin: 'https://www.linkedin.com/in/usmonov-azizbek/',
  },
  contact: {
    phone: '+998901234567',
    email: 'contact@fias.uz',
  },
  terms_of_use: '',
  creator: 'Edu Champ',
};

export { PRODUCT_INFO };
