export const statCardData = [
  {
    title: 'Jami soatlar',
    subtitle: 'Fan 8 kredit',
    value: 82,
    progress: 78,
    progressLabel: "O'tilgan soatlar foizi",
    gradientFrom: '#491872',
    gradientTo: '#401897',
  },
  {
    title: "Ma'ruzalar",
    subtitle: 'Fan 8 kredit',
    value: 11,
    progress: 88,
    progressLabel: "O'tilgan soatlar foizi",
    gradientFrom: '#818cf8',
    gradientTo: '#8342f6',
  },
  {
    title: 'Amaliyotlar',
    subtitle: 'Fan 8 kredit',
    value: 5,
    progress: 65,
    progressLabel: "O'tilgan soatlar foizi",
    gradientFrom: '#fb7185',
    gradientTo: '#e81f56',
  },
  {
    title: 'Mustaqil ish',
    subtitle: 'Fan 8 kredit',
    value: 30,
    progress: 90,
    progressLabel: 'Bajarilgan topshiriqlar',
    gradientFrom: '#60a5fa',
    gradientTo: '#0945ea',
  },
];
